<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUhgdmni\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUhgdmni/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUhgdmni.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUhgdmni\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUhgdmni\appProdProjectContainer([
    'container.build_hash' => 'Uhgdmni',
    'container.build_id' => 'ff9d5d15',
    'container.build_time' => 1599790077,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUhgdmni');
